### ISSUE TITLE
Please correct FSF Address

### ISSUE THREAD

**Issue by nemysis** [mgedmin/pyspacewar#4]
I'm Maintainer for openSUSE and FreeBSD for PySpaceWar

https://build.opensuse.org/package/show/games/pyspacewar

https://www.freshports.org/games/pyspacewar/

Please look and adjust /usr/bin/pyspacewar and GPL.txt

https://www.fsf.org/about/contact/

```\n
[   23s] pyspacewar.noarch: W: no-manual-page-for-binary pyspacewar
[   23s] Each executable in standard binary directories should have a man page.
[   23s] 
[   23s] pyspacewar.noarch: W: incorrect-fsf-address /usr/bin/pyspacewar
[   23s] pyspacewar.noarch: W: incorrect-fsf-address /usr/share/doc/packages/pyspacewar/GPL.txt
[   23s] The Free Software Foundation address in this file seems to be outdated or
[   23s] misspelled.  Ask upstream to update the address, or if this is a license file,
[   23s] possibly the entire file with a new copy available from the FSF.
[   23s] 
[   23s] 2 packages and 0 specfiles checked; 0 errors, 3 warnings.
```

Thanks

**Comment by mgedmin** [comment]
Would you like a new release on PyPI?

**Comment by nemysis** [comment]
Thanks for commit and fixing FSF address.

Yes this is good to have on PyPI.

**Comment by mgedmin** [comment]
https://pypi.python.org/pypi/pyspacewar/0.9.8 is out

**Comment by nemysis** [comment]
Please correct Your Page with newest Version and PyPI link

http://mg.pov.lt/pyspacewar/

**Comment by mgedmin** [comment]
Oh, whoops, I forgot I had a separate web page :)
